version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - img-storage:/data
    ports:
      - "8002:5432"

  webclient:
    build: ./imgserver
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DB=${POSTGRES_DB}
      - STORAGE=/data
    volumes:
      - ./imgserver:/code
      - img-storage:/data
    ports:
      - "8001:8080"
    depends_on:
      - db

volumes:
  img-storage: